name: an_lifecycle_viewmodel
description: "A package for managing ViewModel that depends on an_lifecycle. Similar to Androidx ViewModel."
version: 1.4.0
homepage: https://github.com/aymtools/lifecycle_viewmodel/
issue_tracker: https://github.com/aymtools/lifecycle_viewmodel/issues

topics:
  - viewmodel
  - view-model
  - viewmodels

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  an_viewmodel: any

dev_dependencies:
  flutter_lints: ^4.0.0


flutter:
