name: an_lifecycle_viewmodel
description: "A package for managing ViewModel that depends on an_lifecycle. Similar to Androidx ViewModel."
version: 1.0.1
homepage: https://github.com/aymtools/lifecycle_viewmodel/
issue_tracker: https://github.com/aymtools/lifecycle_viewmodel/issues

topics:
  - viewmodel
  - view-model
  - viewmodels

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cancellable: ^2.0.1
  anlifecycle: ^3.0.1
  an_lifecycle_cancellable: ^1.0.1
  weak_collections: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0


flutter:
