name: an_lifecycle_viewmodel
description: "A package for managing ViewModel that depends on an_lifecycle. Similar to Androidx ViewModel."
version: 0.0.1
homepage: https://github.com/aymtools/lifecycle_viewmodel/
issue_tracker: https://github.com/aymtools/lifecycle_viewmodel/issues

topics:
  - viewModel
  - view-model
  - viewModels

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cancellable: ^2.0.0
  anlifecycle: ^2.0.2
  an_lifecycle_cancellable: ^0.0.3
  weak_collections: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
